preprocess: mel
n_mels: 128
hop_length: 512
blocks:
  - type: cnn
    initial_channels: 16
    num_cnn_layers: 3
    kernel_size: 3
    stride: 1
    padding: 1
    pool_kernel: 2
  - type: gru
    hidden_size: 128
    num_layers: 1
    dropout: 0.0
  - type: fc
    out_features: 128
    dropout: 0.5